---
common_cache_dirs:
  - /var/cache/pacman
  - /var/cache/apt
  - /var/lib/apt/lists

common_copy_bash_skel_to_root: false

# vm.swappiness = 10
common_sysctl_swappiness: false

# net.core.default_qdisc = cake
# net.ipv4.tcp_congestion_control = bbr
common_sysctl_bbr: true

common_create_directories: {}
common_create_files: {}
common_create_configs: {}
