---
# default file for nginx
# install: true  # Use apt to install nginx

# Paths
nginx_web_root: /srv
nginx_html_root: /srv/html
nginx_data_root: /data
nginx_ssl_root: /ssl

nginx_root: /etc/nginx

nginx_sites_enabled_dir: sites-enabled
nginx_sites_available_dir: sites-available
nginx_ssl_snippets: snippets/ssl

nginx_php_enabled: false
nginx_php_version: 7.4 # 7.4 for ubuntu focal
nginx_php_root: "/etc/php/{{ nginx_php_version }}"
nginx_php_pool_root: "{{ nginx_php_root }}/fpm/pool.d"
nginx_fastcgi_listen: "/run/php/php{{ nginx_php_version }}-fpm-user.sock"

nginx_content_enabled: false

# User
nginx_new_user: www-data

# Generate conf.d/upstreams.conf
nginx_upstreams: {}
nginx_upstreams_default:
  transmission: 9091
  jupyter: 8888
  zeronet: 43110
  sync: 8880
  syncthing: 8384
  cockpit: 9999
  code_server: 8080

nginx_config_dirs:
  - conf.d
  - snippets
  - modules-available
  - modules-enabled
  - "{{ nginx_sites_enabled_dir }}"
  - "{{ nginx_sites_available_dir }}"
  - "{{ nginx_ssl_snippets }}"

# config file -> config values dict
nginx_sites_enabled: {}
nginx_sites_disabled: []
nginx_stream: []
nginx_proxy_cache_paths: []
# vars file for nginx
nginx_redirect_code: 301 # Choose 301 or 302
nginx_http_port: 80
nginx_https_port: 443

nginx_php_configs:
  - www-user.conf

nginx_html_files:
  - index.html
