- name: Check if certificate folder exists
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ cert_src | expanduser }}/{{ name }}"
  register: cert_folder

- name: Copy certificates from cert folder
  ansible.builtin.copy:
    src: "{{ cert_src | expanduser }}/{{ item.src }}"
    dest: "{{ ssl_root }}/{{ name }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ name }}/fullchain.cer"
      dest: full.pem
      mode: "0644"
    - src: "{{ name }}/{{ name }}.key"
      dest: "key.pem"
      mode: "0600"
  when: cert_folder.stat.exists
