---
- name: Check if real certificate exists on localhost
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ ssl_cert_src | expanduser }}/{{ ssl_cert_name }}/fullchain.cer"
  register: local_cert_stat
  become: false

- name: Copy real certificates to host
  ansible.builtin.copy:
    src: "{{ ssl_cert_src | expanduser }}/{{ item.src }}"
    dest: "{{ ssl_root }}/{{ ssl_cert_name }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ ssl_cert_name }}/fullchain.cer"
      dest: full.pem
      mode: "0644"
    - src: "{{ ssl_cert_name }}/{{ ssl_cert_name }}.key"
      dest: key.pem
      mode: "0600"
  when: local_cert_stat.stat.exists
  register: real_cert_copy

- name: Copy fallback certificates if real certificates are missing
  ansible.builtin.copy:
    src: "{{ ssl_root }}/_/{{ item.dest }}"
    dest: "{{ ssl_root }}/{{ ssl_cert_name }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: true
  loop:
    - dest: full.pem
      mode: "0644"
    - dest: key.pem
      mode: "0600"
  when: not local_cert_stat.stat.exists
