---
- name: Create html and web root
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_new_user }}"
    group: "{{ nginx_new_user }}"
    mode: "0755"
  loop:
    - "{{ nginx_web_root }}"
    - "{{ nginx_html_root }}"

- name: Create html index
  ansible.builtin.template:
    src: "html/{{ item }}.j2"
    dest: "{{ nginx_html_root }}/{{ item }}"
    mode: "0644"
  loop: "{{ nginx_html_files }}"
