---
# Installation options

# curl -s https://api.github.com/repos/v2fly/v2ray-core/releases/latest | jq -r '.tag_name'
v2ray_version: v5.30.0
v2ray_prefix: /usr/local/opt/v2ray
v2ray_install: /usr/local

# Mapping of ansible architecture to v2ray file name
v2ray_arch:
  x86_64: linux-64
  aarch64: arm64-v8a

v2ray_file: "v2ray-{{ v2ray_arch[ansible_architecture] }}.zip"
v2ray_url: "https://github.com/v2fly/v2ray-core/releases/download/{{ v2ray_version }}/{{ v2ray_file }}"
v2ray_archive: "{{ v2ray_prefix }}/{{ v2ray_version }}.zip"

v2inbounds: []
v2outbounds: []
v2rules: []

v2outbounds_default:
  - protocol: freedom
    tag: direct
  - protocol: blackhole
    tag: blocked
  - protocol: socks
    tag: tor
    settings:
      servers:
        - address: localhost
          port: 9050

v2rules_default:
  - ip:
      - geoip:private
    outboundTag: blocked
  - domain:
      - domain:onion
    outboundTag: tor

v2_ads_domains:
  - vungle.com
  - unityads.unity3d.com
  - supersonicads.com
  - applovin.com
  - applvn.com
  - aarki.net
  - googleads.g.doubleclick.net
  - tpc.googlesyndication.com
  - ironsrc.mob

v2_telegram_ips:
  # https://core.telegram.org/resources/cidr.txt
  - 2a0a:f280::/32
  - 91.105.192.0/23
  - 91.108.4.0/22
  - 91.108.8.0/22
  - 91.108.12.0/22
  - 91.108.16.0/22
  - 91.108.20.0/22
  - 91.108.56.0/22
  - 149.154.160.0/20
  - 185.76.151.0/24
  - 2001:67c:4e8::/48
  - 2001:b28:f23c::/48
  - 2001:b28:f23d::/48
  - 2001:b28:f23f::/48

