---
- name: Find a list of existing cache directories
  stat:
    path: "{{ item }}"
  loop: "{{ cache_dirs }}"
  register: cache_dir_stats

- name: Ensure CACHEDIR.TAG exists in valid cache directories
  copy:
    src: CACHEDIR.TAG
    dest: "{{ item }}/CACHEDIR.TAG"
    mode: 0644
  loop: "{{ cache_dir_stats.results | selectattr('stat.exists') | selectattr('stat.isdir') | map(attribute='item') }}"

- name: Copy bash skel files to /root
  copy:
    src: "bash/skel{{ item }}"
    dest: "/root/{{ item }}"
    backup: true
  loop:
    - .bash_logout
    - .bashrc
    - .profile
  when: copy_bash_skel_to_root

- name: Copy BBR sysctl configuration
  copy:
    src: files/98-bbr.conf
    dest: /etc/sysctl.d/98-bbr.conf
    mode: 0644
