---
- name: Create ssl directories
  ansible.builtin.file:
    path: "{{ ssl_root }}/{{ item }}"
    state: directory
    mode: "0700"
  loop: "{{ ssl_all + ['_'] }}"

- name: Generate default certificate
  ansible.builtin.command:
    cmd: openssl req -nodes -x509 -newkey rsa:2048 -keyout {{ ssl_root }}/_/key.pem -out {{ ssl_root }}/_/full.pem -days 709 -subj /
    creates: "{{ ssl_root }}/_/full.pem"

- name: Copy certificates
  ansible.builtin.include_tasks: copycert.yml
  loop: "{{ ssl_all }}"
  loop_control:
    loop_var: ssl_cert_name
