---
- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: restart php-fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: start php-fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: yes
