---
# handlers file for basic
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start v2ray
  ansible.builtin.service:
    name: v2ray
    state: started
    enabled: yes

- name: Restart v2ray
  ansible.builtin.service:
    name: v2ray
    state: restarted
