---
- name: Create PHP pool configuration
  ansible.builtin.template:
    src: "php/{{ item }}.j2"
    dest: "{{ nginx_php_pool_root }}/{{ item }}"
    mode: "0644"
  loop: "{{ nginx_php_configs }}"
  notify: restart php-fpm
