---
- name: Install unzip
  ansible.builtin.apt:
    name: unzip

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "/usr/local/opt/v2ray-{{ v2ray_version }}"
    - "{{ v2ray_install }}"
    - "{{ v2ray_install }}/bin"
    - "{{ v2ray_install }}/etc/v2ray"

- name: Download and extract V2Ray archive
  ansible.builtin.unarchive:
    src: "{{ v2ray_url }}"
    dest: "/usr/local/opt/v2ray-{{ v2ray_version }}"
    remote_src: true
    creates: "/usr/local/opt/v2ray-{{ v2ray_version }}/v2ray"
    checksum: "{{ v2ray_checksum[ansible_facts.architecture] }}"
  notify:
    - Restart v2ray

- name: Create symlink to current version
  ansible.builtin.file:
    src: "/usr/local/opt/v2ray-{{ v2ray_version }}"
    dest: "/usr/local/opt/v2ray"
    state: link
  notify:
    - Restart v2ray

- name: Link binary to system path
  ansible.builtin.file:
    src: "/usr/local/opt/v2ray/v2ray"
    dest: "{{ v2ray_install }}/bin/v2ray"
    state: link

- name: Copy service file
  ansible.builtin.template:
    src: v2ray.service
    dest: /etc/systemd/system/
    mode: "0644"
  notify:
    - Reload systemd
    - Start v2ray
