---
- name: Install Packages (Ubuntu)
  ansible.builtin.import_tasks: install_general.yml
  when: ansible_facts.os_family == "Debian"
  tags: install

- name: Install Packages (Arch)
  ansible.builtin.import_tasks: install_arch.yml
  when: ansible_facts.os_family == "Archlinux"
  tags: install

# - debug:
#     msg: "{{ lookup('template', 'config.yml.j2') }}"

- name: Copy config file
  ansible.builtin.copy:
    content: >
      {{ v2ray_inbounds | local.infra.v2ray_config(v2ray_outbounds_default,
      v2ray_outbounds, v2ray_rules_default, v2ray_ads_domains,
      v2ray_telegram_ips, v2ray_rules) | to_nice_json(indent=2) }}
    dest: "{{ v2ray_install }}/etc/v2ray/config.json"
    mode: "0644"
  notify:
    - Restart v2ray
