---
- name: Install v2ray
  community.general.pacman:
    name: v2ray
    state: present
  notify: Start v2ray
  register: pacman_result
  failed_when: false

- name: Update variables
  ansible.builtin.set_fact:
    v2ray_install: ""

- name: Copy service file
  ansible.builtin.template:
    src: v2ray.service
    dest: /etc/systemd/system/
    mode: "0644"
  notify:
    - Reload systemd
    - Start v2ray
