---
- name: Install v2ray
  community.general.pacman:
    name: v2ray
    state: present
  notify: Start v2ray
  ignore_errors: true

- name: Update variables
  set_fact:
    v2ray_install: ""

- name: Copy service file
  template:
    src: v2ray.service
    dest: /etc/systemd/system/
  notify:
    - Reload systemd
    - Start v2ray
