---
- name: Install Packages (Ubuntu)
  ansible.builtin.import_tasks: install_general.yml
  when: ansible_os_family == "Debian"
  tags: install

- name: Install Packages (Arch)
  ansible.builtin.import_tasks: install_arch.yml
  when: ansible_os_family == "Archlinux"
  tags: install

# - debug:
#     msg: "{{ lookup('template', 'config.yml.j2') }}"

- name: Copy config file
  ansible.builtin.copy:
    content: "{{ lookup('template', 'config.yml.j2') | from_yaml | to_json }}"
    dest: "{{ v2ray_install }}/etc/v2ray/config.json"
  notify:
    - Restart v2ray
